// <auto-generated />
using KonyvlistaWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonyvlistaWebApp.Migrations
{
    [DbContext(typeof(KonyvtarDbContext))]
    partial class KonyvtarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KonyvlistaWebApp.Models.Konyv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KiadasEve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Konyvek");
                });
#pragma warning restore 612, 618
        }
    }
}
